name: Build Android app
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Android debug build
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
      - name: Upload to KaneAI
        env:
          LAMBDATEST_USERNAME: ${{ secrets.LAMBDATEST_USERNAME }}
          LAMBDATEST_ACCESS_KEY: ${{ secrets.LAMBDATEST_ACCESS_KEY }}
        run: |
          APK_FILE=$(find composeApp/build/outputs/apk/debug -name "*.apk" | head -n 1)
          curl -X POST "https://manual-api.lambdatest.com/app/uploadFramework" \
            -H "Authorization: Basic $(echo -n $LAMBDATEST_USERNAME:$LAMBDATEST_ACCESS_KEY | base64)" \
            -F "appFile=@$APK_FILE" \
            -F "name=$(basename $APK_FILE)" \
            -F "type=android"
