name: Build Android app

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    # Only run build in template repo
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Android debug build
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
