name: Build Android app
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Android debug build
        run: ./gradlew assembleDebug --stacktrace
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
     
      - name: Upload to LambdaTest
        env:
          LAMBDATEST_USERNAME: ${{ secrets.LAMBDATEST_USERNAME }}
          LAMBDATEST_ACCESS_KEY: ${{ secrets.LAMBDATEST_ACCESS_KEY }}
        run: |
          echo "🔎 Using LambdaTest Username: $LAMBDATEST_USERNAME"
          
          APK_FILE=$(find composeApp/build/outputs/apk/debug -name "*.apk" | head -n 1)
          if [ -z "$APK_FILE" ]; then
            echo "❌ No APK file found!"
            exit 1
          fi
          
          AUTH=$(echo -n "$LAMBDATEST_USERNAME:$LAMBDATEST_ACCESS_KEY" | base64)
          
          echo "⬆️ Uploading $APK_FILE to LambdaTest..."
          curl --fail -X POST "https://manual-api.lambdatest.com/app/upload/realDevice" \
            -H "Authorization: Basic $AUTH" \
            -F "appFile=@$APK_FILE" \
            -F "name=MyApp"

